
development:
  adapter: postgresql
  database: vegemite_dev
  host: localhost

test:
  adapter: postgresql
  database: vegemite_test
  host: localhost

production:
  adapter: postgresql
  database: vegemite
  host: localhost
